version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/room-booking-system  # Update this line to use 'mongo' instead of 'localhost'
    env_file:
      - ./api/.env
    depends_on:
      - mongo  # Ensure that the 'mongo' service starts before 'api'

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db  # Optional: To persist MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
